theme: jekyll-theme-minimal
title: "Learning to Find Similarities in Equations"
description: "We provide a dataset of equations represented as PNG-images and Latex code. This dataset is useful for learning to detect similarities in equations."
show_downloads: "true"
logo: "docs/ls8.png"